repositoryName: helpdesk-phone
repositoryOwner: commexcom
imageTag: 6119cb687f491890c0efcd3325fe5815ec732afc-stage
replicaCount: 2
service:
  enabled: true
  type: ClusterIP
  internalPort: 3000
  externalPort: 443
ingress:
  enabled: true
  className: "nginx"
  annotations:
    {
      nginx.ingress.kubernetes.io/ssl-redirect: "true",
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true",
      nginx.ingress.kubernetes.io/rewrite-target: /,
    }
  hosts:
    - host: telefone.guaruja.sp.gov.br
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - telefone.guaruja.sp.gov.br
      secretName: guarujaspgovbr-tls
